# Generated by Django 4.0.4 on 2022-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=True, upload_to='', verbose_name='images'),
            preserve_default=False,
        ),
    ]
