# Generated by Django 4.0.4 on 2022-04-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
