# Generated by Django 4.0.4 on 2022-04-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='txt',
        ),
    ]
