# Generated by Django 4.0.4 on 2022-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_img_remove_post_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='txt',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
