# Generated by Django 4.0.4 on 2022-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=True, upload_to='', verbose_name='/image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='txt',
            field=models.TextField(verbose_name='/text/'),
        ),
    ]
