# Generated by Django 4.0.4 on 2022-04-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_img_alter_post_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Char',
        ),
    ]
