# Generated by Django 4.0.4 on 2022-04-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_text_post_char'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Char',
            new_name='text',
        ),
    ]
