# Generated by Django 4.0.4 on 2022-04-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_char_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='char',
        ),
    ]
